config/routes.rb
Rails.application.routes.draw do
  get 'docs/show'
  namespace :admin do
    resources :projects
    resources :users

    root to: "projects#index"
  end

  root "home#index"

  devise_for :users

  resources :projects do
    resources :posts do
      resources :comments
    end
    resources :documents, only: [:create, :index, :show, :destroy]
  end

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  get "/notadmin", to: "home#notadmin"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :documents, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :projects
  has_many :posts
  has_many :comments
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      if !signed_in?
        redirect_to new_user_session_path
      else
        if current_user.admin == false
          redirect_to notadmin_path
        end
      end
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    add_flash_types :info, :error, :warning
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if signed_in?
      redirect_to projects_path
    end
  end

  def error
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :correct_user, only: %i[ edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
    
  end

  # GET /projects/1 or /projects/1.json
  def show
    @project = Project.find(params[:id])
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit

  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def correct_user
      if !current_user
        redirect_to new_user_session_path, notice: "Can't Perform Action"
      elsif current_user
        if current_user.id != set_project.user_id
          redirect_to projects_path, notice: "Can't Perform Action"
        end
      end

    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :user_id)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.erb
<div class="text-center">

</br>
</br>
</br>
</br>
    <div>
        <%= image_tag "basecamp_img_logo.png", height: 150, class: "image" %>
    </div>

    <h1>COLLABORATE</h1>
    <h5>A project management tool for developers</h5>
    </br>

    <div>

        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
        <%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>

    </div>



</div>

app/views/home/notadmin.html.erb
<h1>User not Allowed Except Admin </h1>
</br>
<p>Login in admin</p>
<p>Steps: README.md</p>

app/views/layouts/_navbar.html.erb
<div class="container-fluid">

<nav class="navbar navbar-expand-md bg-primary navbar-dark py-2 px-3">

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
</button>
  
  <%if !user_signed_in?%>

    <a class="navbar-brand" href="/">My Basecamp</a>
    
  <%else%>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
          <ul class="navbar-nav">

            <li class="nav-item">
              <%= link_to 'Add Project', new_project_path, class:"nav-link" %>
            </li>

            <li class="nav-item">
              <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
            </li>


            <li class="nav-item">
              <%= link_to 'Projects', projects_path, class:"nav-link" %>
            </li>

            <li class="nav-item">
                <%= link_to 'Admin', admin_projects_path, class:"nav-link" %>
            </li>

            <li class="nav-item">
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>

            </li>


          </ul>
        </div>
  <%end%>
</nav>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Basecamp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style>
    body {margin:0;}

    .navbar {
      overflow: hidden;
      background-color: #333;
      position: fixed;
      top: 0;
      width: 100%;
      z-index: 9999;
    }

    .navbar li {
      float: left;
      display: block;
      text-decoration: none;
      font-size: 17px;
    }

    .navbar a:hover {
      background: #ddd;
    }

    </style>

  </head>

<body>

  <div class="card-body container-fluid p-4 my-4">
    <%= render partial: "layouts/navbar"%>
    <% if signed_in? %>
      <% if current_user.admin == false %>
        <div class="card-body">
          <h3 >Current Status: User </h3>
        </div>
      <% else %>
      <div class="card-body">
        <h3>Current Status: Admin </h3>
      </div>
      <% end %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  <div>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
  
  <% if signed_in? %>
    <div>
      <%= form.hidden_field :user_id, value: current_user.id %>
    </div>
  <%end%>

  <div>
    <p><%= form.submit %></p>
  </div>
<% end %>

app/views/projects/_navbar.html.erb
<nav class="navbar navbar-expand bg-body-tertiary fixed-top-start">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            </a>
            <ul class="dropdown-menu">
              <li><%= button_to "Delete Project", @project, method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-secondary" %></li>
              <li><%= link_to "Edit", edit_project_url(@project), class:"btn btn-secondary btn-sm" %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>
<%= link_to "New project", new_project_path, class: "btn btn-success col-lg-3" %>
<div class="card-body">
<div id="projects" class="card-body container-fluid p-3 my-3 border">
<% if !current_user %>
    <%= "kindly login" %>
    </br>
    </br>
    <%= link_to "Login",  new_user_session_path, class:"btn btn-primary"%>
<% else %>
    <% @projects.each do |project| %>
      <% if current_user.id == project.user_id %>
        <%= render project %>
        <p>
          <%= link_to "Show this project", project, class: "btn btn-primary col-lg-3" %>
        </p>
      <% end %>
    <% end %>
  </div>
  
<% end %>
</div> 

app/views/projects/new.html.erb
<div class="text-center">

<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<h2>Project</h2>

<%= render @project %>

<div>
  <a><%= link_to "Edit this project", edit_project_path(@project) %> |</a>
  <%= link_to "Back to projects", projects_path %>
  <%= button_to "Destroy this project", @project, method: :delete %>
</div>